name: quadruped_pympc_env
channels:
- conda-forge
- robostack-staging
dependencies:
- python
- casadi
- numpy
- matplotlib
- jaxlib
- jax
- meshcat-python 
- scipy 
- pinocchio
- adam-robotics[all]
- compilers 
- cmake 
- pkg-config 
- make 
- pip:
  - mujoco

